### ISSUE TITLE
use sha256 instead of sha1

### ISSUE THREAD

**Issue by gossi** [jlhonora/lsusb#11]
Because brew is telling me to do so:

```
$ brew upgrade
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!
```

**Comment by jlhonora** [comment]
Hi Thomas, thanks for reporting this. We did address it in https://github.com/jlhonora/homebrew-lsusb/pull/2 , but it seems that wasn't enough. I'll have a closer look and update this accordingly.

**Comment by jlhonora** [comment]
Does running `brew update && brew upgrade` fix the problem?

**Comment by gossi** [comment]
Nope, unfortunately not, see log (I run it twice, just to be sure):

```
$ brew update && brew upgrade
Already up-to-date.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!
```

**Comment by gossi** [comment]
Nope, unfortunately not, see log (I run it twice, just to be sure):

```
$ brew update && brew upgrade
Already up-to-date.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
Please report this to the jlhonora/lsusb tap!
```

**Comment by jlhonora** [comment]
Ok, thanks. Note that a quick and dirty workaround is to do:

```
wget https://raw.githubusercontent.com/jlhonora/lsusb/master/lsusb && chmod +x lsusb && mv lsusb /usr/local/bin/
```

But I'd rather solve this problem anyhow. What's the output of `brew --version` and `brew log -p lsusb`?

**Comment by gossi** [comment]
There you go:

```
$ brew --version
Homebrew 0.9.9 (git revision 06fe3; last commit 2016-08-10)
Homebrew/homebrew-core (git revision 237c; last commit 2016-06-03)
```

```
$ brew log -p lsusb
commit 9d37827606592e95ea22ceb2e33496c63a7cace3
Author: jlhonora <...>
Date:   Mon Feb 24 10:54:36 2014 -0300

    Moved to version 1.0

diff --git a/lsusb.rb b/lsusb.rb
index 562d506..31196a3 100644
--- a/lsusb.rb
+++ b/lsusb.rb
@@ -4,12 +4,12 @@ class Lsusb < Formula
   homepage 'https://github.com/jlhonora/lsusb'
   head 'https://github.com/jlhonora/lsusb', :using => :git

-  url 'https://github.com/jlhonora/lsusb/releases/download/0.2/lsusb-0.2.tar.gz'
-  sha1 '00e99f1f9fb15ae5fcb4261d354d1dac0b8ee9fb'
+  url 'https://github.com/jlhonora/lsusb/releases/download/1.0/lsusb-1.0.tar.gz'
+  sha1 'eae97f7c3239ba459e1dc1322eb449026376e545'

   def install
     bin.install 'lsusb'
-    man1.install 'man/lsusb.1'
+    man8.install 'man/lsusb.8'
   end

 end

commit ddd6caa23d058ba04485dbeeee87a7628702d59a
Author: Edward Anderson <...>
```

**Comment by jlhonora** [comment]
Sorry for the delay. It looks like you still have an old version of the tap.

Maybe try with:

```
brew uninstall lsusb
brew untap jlhonora/lsusb
brew tap jlhonora/lsusb
brew install lsusb
```

**Comment by gossi** [comment]
Yep. That's it. Weird, since the taps are the same, thought there is no difference. However it worked:

```
$ brew doctor
Your system is ready to brew.
```
